# Generated by Django 4.1.1 on 2022-09-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_photo_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='slug',
        ),
    ]
