# Generated by Django 4.1.1 on 2022-09-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_options_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Общая цена на товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price_per_item',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Общая цена на товар'),
        ),
    ]
